### ISSUE TITLE
psl option --psl-report not reconized

### ISSUE THREAD

**Issue by Masshat** [tmeissner/vhdl_verification#1]
Hi tmeissner, hope you are right, 
I have cloned your repo vhdl_verification and i find your work very awesome, there are good example to learn verification using osvvm, plus psl assertions.

But I have an issue when I try to compile the  osvvm_fsm_coverage examples, here is the log after performing make:
"Analyse OSVVM library ...
Analyse & elaborate test ...
Run test ...
./osvvm_fsm_coverage:error: unknown option '--psl-report=osvvm_fsm_coverage.json', try --help
make: **\* [Makefile:11: sim] Error 1"

$ghdl -v
GHDL 0.33 (20150921) [Dunoon edition]
 Compiled with GNAT Version: 6.2.1 20160830
 GCC back-end code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2015 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Can you help me or give me some indications to run this examples. by the way I have also a small example of CRV and FC at https://github.com/Masshat/osvvm_verification, don't hesitate to give me some feedback on how the testbench is written and how can i improve the log output.

Kind Regards,
Masshat.

**Comment by tmeissner** [comment]
Do you have GHDL self compiled from the  Github repository? Because the PSL report feature is relatively new. It works with my GHDL version:

```
$ ghdl -v
GHDL 0.34dev (20151126) [Dunoon edition]
 Compiled with GNAT Version: GPL 2015 (20150428-49)
 llvm code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2015 Tristan Hingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Masshat** [comment]
Yes, I have this version https://aur.archlinux.org/packages/ghdl/ and here is the PKGBUILD : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ghdl

I have also installed the 0.34Dev from the github repo, but it generate another error such as cannot file std and v08 is no compatible.

Or maybe there is some option to pass to the compiler?

**Comment by tmeissner** [comment]
The PKGBUILD uses GHDL tag 0.33, which is from the last year. That version don't know the `--psl-report` option, which was added very recently in May 2016 I think. It would be better to investigate why your self compiled 0.34dev version don't works. I think, I have heard of these errors regarding std library before. Maybe you can find the solution in the closed bug reports of GHDL.

**Comment by Masshat** [comment]
Here is the error I get with the new version of GHDL : Analyse OSVVM library ...
ghdl:warning: library std does not exists for v08
ghdl:warning: library ieee does not exists for v08
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/ghdl1: cannot find "std" library
ghdl: compilation error
make: **\* [Makefile:19: work/osvvm/CoveragePkg.o] Error 1

$ ghdl -v
GHDL 0.34dev (20151126) [Dunoon edition]
 Compiled with GNAT Version: 6.2.1 20160830
 GCC back-end code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2015 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Do you have faced this issue or not? 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ghdl-gcc-git this is the PKGBUILD aking the ghdl from github. Do you have any idea how to resolve this, I will look in ghdl issue  by the way.

Regards.

**Comment by Masshat** [comment]
Issue Closed, I have recompiled GHDL with the current version of GitHub repo and it works fine for all the test-cases.

**Comment by tmeissner** [comment]
Good. If you have other questions, don't hesitate to ask :)
